// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface ITokenSystem {
  function mint(uint256 _tokenSequence, bytes memory metadata) external;
}
