[profile.default]
solc_version = "0.8.13"
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 3000
verbosity = 1
src = "src"
test = "test"
out = "out"
allow_paths = ["../../node_modules", "../../../../packages"]
extra_output_files = [
  "abi",
  "evm.bytecode"
]
fs_permissions = [{ access = "read", path = "./"}]

[profile.optimism-testnet]
eth_rpc_url = "https://optimism-goerli.infura.io/v3/26423ae5f7f645398aa0f783e7ced5a6"

[profile.hackathon-testnet]
eth_rpc_url = "https://lattice-goerli-sequencer.optimism.io"

[profile.lattice-testnet]
eth_rpc_url = "https://follower.testnet-chain.linfra.xyz"

[etherscan]
testnet = { key = "${ETHERSCAN_API_KEY}", url="https://api-sepolia.etherscan.io/"}
